### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by CLUBMATEjka**
added bable for es6 support
npm run build must be executed before uploading to the server so all es6 stuff will be converted to es2015

### CODE REVIEW

**Comment by femot** [comment]
@joelfi take that!

**Comment by AppleBetas** [comment]
I'm proud of you all. <3

**Comment by joelfi** [comment]
I'm currently rewriting arrow functions to support ES5. Leaving this open until the code is fully converted to ES5.

**Comment by joelfi** [comment]
No Babel needed, the code is now fully ES5. This issue can be closed if wanted @nullpixel1.

**Comment by nullpixel1** [comment]
Merge ?

**Comment by joelfi** [comment]
No merge needed, code is 100% ES5.

**Pull request closed without merging**
